### ISSUE TITLE
[Request] Update QGIS

### ISSUE THREAD

**Issue by ZQyou** [OSC/bc_osc_qgis#4]
1. Add Pitzer cluster
2. Add version option. Available versions are
```
$ ml av qgis
qgis/3.4.12 (D)    qgis/3.16.14    qgis/3.22.1
```

**Comment by johrstrom** [comment]
@gbyrketosc can you pick this up?

**Comment by ghost** [comment]
This has been completed.  It will be pushed to Production tomorrow.
